    
package Visual.Adm;

import Visual.Adm.CadastroVeterinarios;
import Visual.*;

import com.mycompany.clinicaveterinaria.*;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
/**
 *
 * @author pauli
 */
public class MenuAdministração extends javax.swing.JPanel {
    Clinica petShop;
    
    public MenuAdministração(Clinica clinica) {
        initComponents();
        this.petShop = clinica;
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Consultas = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        cadastrosGerais = new javax.swing.JButton();
        VoltarMenuAdm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 250, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Consultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Consultas.setText("Consultas/Edições");
        Consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultasActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/kMPJHvG.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        cadastrosGerais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrosGerais.setText("Cadastros Gerais");
        cadastrosGerais.setToolTipText("");
        cadastrosGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrosGeraisActionPerformed(evt);
            }
        });

        VoltarMenuAdm.setText("Voltar");
        VoltarMenuAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarMenuAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadastrosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(VoltarMenuAdm)
                        .addGap(114, 114, 114)))
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel30)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(cadastrosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VoltarMenuAdm)
                .addGap(48, 48, 48))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Adminstração");

        jLabel32.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/Ifajv0U.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultasActionPerformed
       // dentro do seu método de ação
         Window window = SwingUtilities.getWindowAncestor(this); // 'this' é o painel onde está o botão

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 600);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        MenuGerenciamento painel = new MenuGerenciamento(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }//GEN-LAST:event_ConsultasActionPerformed

    private void cadastrosGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrosGeraisActionPerformed
        // dentro do seu método de ação
         Window window = SwingUtilities.getWindowAncestor(this); // 'this' é o painel onde está o botão

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 600);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        MenuCadastrosGerais painel = new MenuCadastrosGerais(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }//GEN-LAST:event_cadastrosGeraisActionPerformed

    private void VoltarMenuAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarMenuAdmActionPerformed
        // dentro do seu método de ação
         Window window = SwingUtilities.getWindowAncestor(this); // 'this' é o painel onde está o botão

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 600);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        MenuPrincipal painel = new MenuPrincipal(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }                                            

    private void AdmActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // dentro do seu método de ação
         Window window = SwingUtilities.getWindowAncestor(this); // 'this' é o painel onde está o botão

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 600);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        CadastroVeterinarios painel = new CadastroVeterinarios(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }//GEN-LAST:event_VoltarMenuAdmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultas;
    private javax.swing.JButton VoltarMenuAdm;
    private javax.swing.JButton cadastrosGerais;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
