    
package Visual;
import Visual.Veterinario.LoginVeterinario;
import Visual.Tutor.LoginTutor;
import Visual.Adm.MenuAdministração;
import com.mycompany.clinicaveterinaria.*;
import java.awt.Window;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Ana
 */

public class MenuPrincipal extends javax.swing.JPanel {
    Clinica petShop;
    /**
     * Creates new form Agendamento
     */
    public MenuPrincipal(Clinica clinica) {
        initComponents();
        this.petShop = clinica;
        
    }
    
    public static void main(String[] args) {
        // Cria o objeto da clínica (ou recebe de onde você quiser)
        Clinica clinica = new Clinica("Vida Animal");
        

        // Cria o frame (janela)
        JFrame frame = new JFrame("Tela de Teste");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Cria o painel passando o petShop
        MenuPrincipal painel = new MenuPrincipal(clinica);

        // Adiciona o painel no frame
        frame.getContentPane().add(painel);

        // Define tamanho da janela
        frame.setSize(800, 600); // ou qualquer tamanho que preferir

        // Centraliza na tela
        frame.setLocationRelativeTo(null);

        // Torna visível
        frame.setVisible(true);
        
        
    }
    
    public void criarObjetos() {
    // Tutores
    Tutor t1 = new Tutor("Juliana Silva", "123", "juliana.silva@gmail.com", 7199123, "Rua das Acácias, 101");
    Tutor t2 = new Tutor("Carlos Eduardo", "98765432100", "carlos.edu@gmail.com", 71997654, "Avenida Central, 200");
    Tutor t3 = new Tutor("Fernanda Moura", "45678912300", "fernanda.moura@gmail.com", 7199876, "Rua São Jorge, 85");

    // Animais
    Animal a1 = new Animal("Luna", "Golden Retriever", "15/03/2019", t1);
    Animal a2 = new Animal("Tico", "Shih Tzu", "09/11/2021", t1);
    Animal a3 = new Animal("Thor", "Pastor Alemão", "01/01/2020", t2);
    Animal a4 = new Animal("Mel", "Gato Siamês", "12/08/2018", t3);
    Animal a5 = new Animal("Zig", "Poodle", "05/05/2017", t3);

    // Associar animais aos tutores
    t1.addAnimais(a1);
    t1.addAnimais(a2);
    t2.addAnimais(a3);
    t3.addAnimais(a4);
    t3.addAnimais(a5);

    // Adicionar tutores no petShop
    petShop.addTutor(t1);
    petShop.addTutor(t2);
    petShop.addTutor(t3);

    // Especialidades
    Especialidade esp1 = new Especialidade("Cardiologista", 80);
    Especialidade esp2 = new Especialidade("Ortopedista", 70);
    Especialidade esp3 = new Especialidade("Dermatologista", 60);

    petShop.addEspecialidades(esp1);
    petShop.addEspecialidades(esp2);
    petShop.addEspecialidades(esp3);

    // Veterinários
    Veterinario vet1 = new Veterinario("Marcos", "123", "marcos.vet@gmail.com", 7199100, esp1, 123, "08h as 12h");
    Veterinario vet2 = new Veterinario("Bianca", "100002", "bianca.vet@gmail.com", 7199200, esp2, 7788, "14h as 18h");
    Veterinario vet3 = new Veterinario("Rita", "100003", "rita.vet@gmail.com", 719300, esp3, 8899, "08h as 12h");

    petShop.addVeterinarios(vet1);
    petShop.addVeterinarios(vet2);
    petShop.addVeterinarios(vet3);

    // Datas e horários para agendamento
    LocalDate data1 = LocalDate.of(2025, 7, 15);
    LocalDate data2 = LocalDate.of(2025, 7, 16);
    LocalTime hora1 = LocalTime.of(8, 0);
    LocalTime hora2 = LocalTime.of(10, 20);
    LocalTime hora3 = LocalTime.of(14, 0);

    // Agendamentos
    Agendamento ag1 = new Agendamento(data1, hora1, esp1, a1);
    Agendamento ag2 = new Agendamento(data1, hora2, esp2, a3);
    Agendamento ag3 = new Agendamento(data2, hora3, esp3, a4);

    // Adicionando agendamentos aos animais
    a1.addListaAgendamentos(ag1);
    a3.addListaAgendamentos(ag2);
    a4.addListaAgendamentos(ag3);
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Consultar = new javax.swing.JButton();
        Veterinario1 = new javax.swing.JButton();
        criar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        Adm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 250, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Consultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Consultar.setText("Tutor");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Veterinario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Veterinario1.setText("Veterinario");
        Veterinario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Veterinario1ActionPerformed(evt);
            }
        });

        criar.setText("criar Objetos");
        criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarActionPerformed(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/kMPJHvG.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        Adm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Adm.setText("Administração");
        Adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(criar)
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Veterinario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Adm, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(criar)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Adm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(Veterinario1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addComponent(jLabel30))
        );

        Consultar.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Meni Telinha");

        jLabel32.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/Ifajv0U.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        
         Window window = SwingUtilities.getWindowAncestor(this);

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(700, 500);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        LoginTutor painel = new LoginTutor(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }//GEN-LAST:event_ConsultarActionPerformed

    private void Veterinario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Veterinario1ActionPerformed
       // dentro do seu método de ação
         Window window = SwingUtilities.getWindowAncestor(this); // 'this' é o painel onde está o botão

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 600);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        LoginVeterinario painel = new LoginVeterinario(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }//GEN-LAST:event_Veterinario1ActionPerformed

    private void criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarActionPerformed
        criarObjetos();
        JOptionPane.showMessageDialog(this, "Objetos criados com sucesso!");
    }//GEN-LAST:event_criarActionPerformed

    private void AdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmActionPerformed
        // dentro do seu método de ação
         Window window = SwingUtilities.getWindowAncestor(this); // 'this' é o painel onde está o botão

         if (window != null) {
           window.dispose(); // fecha a janela que contém esse painel
          }
         
        JFrame frame = new JFrame("Agendamento");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 500);// ajusta tamanho da janela ao tamanho do painel e componentes
        frame.setLocationRelativeTo(null); // centraliza

        MenuAdministração painel = new MenuAdministração(petShop);
        frame.add(painel);

        frame.setVisible(true);
    }//GEN-LAST:event_AdmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adm;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Veterinario1;
    private javax.swing.JButton criar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
